name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp | modified by Curri'
runs:
  using: 'node16'
  main: 'main.mjs'
branding:
  icon: 'bell'
  color: 'yellow'