name: 'Slack Notify'
description: 'This action will send a notification to Slack'
author: 'rtCamp | modified by Curri'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
branding:
  icon: 'bell'
  color: 'yellow'